apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: boardgame-deployment
  namespace: boardgame
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: 533267043749.dkr.ecr.ap-south-1.amazonaws.com/himalaya7087:boardgame-app-41 # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
